version: '2'
services:
  node:
    build: .
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    command: yarn watch
    volumes:
      - ./src:/usr/app/src
      - ./tsconfig.json:/usr/app/tsconfig.json
    ports:
      - '9229:9229'
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.development.conf:/etc/nginx/nginx.conf
    ports:
      - '3000:3000'
