version: '2'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    command: yarn serve
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.production.conf:/etc/nginx/nginx.conf
    ports:
      - '3000:3000'
